# Generated by Django 5.0.6 on 2025-11-29 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrodiario',
            name='agua_ml',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrodiario',
            name='calorias_consumidas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrodiario',
            name='comida',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrodiario',
            name='estado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='registrodiario',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrodiario',
            name='porciones',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
