# Generated by Django 5.0.6 on 2025-11-29 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='calorias_recomendadas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='carbohidratos_g',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='grasas_g',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='peso_actual',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='proteina_g',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
