# Generated by Django 5.0.6 on 2025-12-12 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_cita_calorias_recomendadas_cita_carbohidratos_g_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='calorias_recomendadas',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='carbohidratos_g',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='grasas_g',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='peso_actual',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='proteina_g',
        ),
    ]
