# Generated by Django 5.0.6 on 2025-12-12 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citas', '0003_remove_cita_calorias_recomendadas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanAlimenticio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField(blank=True, null=True)),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('calorias', models.IntegerField(blank=True, null=True)),
                ('proteina_g', models.IntegerField(blank=True, null=True)),
                ('carbohidratos_g', models.IntegerField(blank=True, null=True)),
                ('grasas_g', models.IntegerField(blank=True, null=True)),
                ('verduras', models.CharField(blank=True, max_length=255)),
                ('frutas', models.CharField(blank=True, max_length=255)),
                ('recomendaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes', to='citas.cita')),
            ],
            options={
                'ordering': ['-fecha', '-hora', '-created_at'],
            },
        ),
    ]
